const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('api',{
  login:(d)=>ipcRenderer.invoke('login',d),
  getState:()=>ipcRenderer.invoke('getState'),
  getProducts:()=>ipcRenderer.invoke('getProducts'),
  searchProducts:(term)=>ipcRenderer.invoke('searchProducts',term),
  getClients:()=>ipcRenderer.invoke('getClients'),
  searchClients:(term)=>ipcRenderer.invoke('searchClients',term),
  saveClient:(payload)=>ipcRenderer.invoke('saveClient',payload),
  deleteClient:(payload)=>ipcRenderer.invoke('deleteClient',payload),
  addClientPurchase:(payload)=>ipcRenderer.invoke('addClientPurchase',payload),
  saveDB:(db,user,accion,detalle)=>ipcRenderer.invoke('db:save',db,user,accion,detalle),
  saveProduct:(payload)=>ipcRenderer.invoke('saveProduct',payload),
  deleteProduct:(payload)=>ipcRenderer.invoke('deleteProduct',payload),
  newSale:(d)=>ipcRenderer.invoke('newSale',d),
  backup:()=>ipcRenderer.invoke('backup'),
  backupCreate:()=>ipcRenderer.invoke('backup:create'),
  ticket:(venta,negocio)=>ipcRenderer.invoke('ticket:create',venta,negocio),
  printers:()=>ipcRenderer.invoke('system:printers')
});
