let db=null, user=null, view='dashboard', editingProduct=null, cart=[];
const $=s=>document.querySelector(s); const money=n=>'$ '+Number(n||0).toLocaleString('es-AR',{minimumFractionDigits:2,maximumFractionDigits:2});
async function init(){ db=await window.api.getDB(); renderLogin(); }
function save(accion,detalle){ return window.api.saveDB(db,user,accion,detalle).then(x=>{db=x; render();}); }
function renderLogin(){ $('#app').innerHTML=`<div class="login"><div class="card"><div class="brand">PetroPOS</div><p class="sub">Sistema de Gestión Comercial</p><label>Usuario</label><input id="u" value="admin"><label>Contraseña</label><input id="p" type="password" value="admin123"><div class="toolbar"><button onclick="login()">Ingresar</button></div><p class="muted">Admin: admin/admin123<br>Vendedor: vendedor/venta123</p></div></div>`; $('#p').addEventListener('keydown',e=>{if(e.key==='Enter')login();}); }
function login(){ const u=$('#u').value.trim(), p=$('#p').value; const found=db.usuarios.find(x=>x.usuario===u&&x.clave===p); if(!found) return alert('Usuario o contraseña incorrectos'); user=found; view='dashboard'; render(); }
function layout(content){ const navs=[['dashboard','🏠 Inicio'],['ventas','💰 Ventas'],['productos','📦 Productos'],['stock','📊 Stock'],['clientes','👥 Clientes'],['proveedores','🚚 Proveedores'],['caja','💳 Caja'],['reportes','📈 Reportes'],['config','⚙ Configuración'],['tecnico','🔧 Técnico']]; $('#app').innerHTML=`<div class="layout"><aside class="side"><div class="logo">PetroPOS</div>${navs.map(n=>`<button class="nav ${view===n[0]?'active':''}" onclick="view='${n[0]}';render()">${n[1]}</button>`).join('')}<div style="flex:1"></div><button class="nav" onclick="user=null;renderLogin()">Salir</button></aside><main class="main"><header class="top"><div><b>${db.negocio.nombre||'PetroPOS'}</b><span class="muted"> · v0.5.0 Pro Piloto</span></div><div>${user.nombre} · ${user.rol} · Caja: ${db.caja.abierta?'ABIERTA':'CERRADA'}</div></header><section class="content">${content}</section></main></div>`; }
function render(){ const pages={dashboard,ventas,productos,stock,clientes,proveedores,caja,reportes,config,tecnico}; layout(pages[view]()); afterRender(); }
function afterRender(){ if(view==='ventas'){ const inp=$('#scan'); if(inp) inp.focus(); } }
function dashboard(){ const ventasHoy=db.ventas.filter(v=>v.fecha.slice(0,10)===new Date().toISOString().slice(0,10)); const total=ventasHoy.reduce((a,v)=>a+v.total,0); const low=db.productos.filter(p=>p.activo&&Number(p.stock)<=Number(p.minimo)); return `<h1>Dashboard</h1><div class="grid g4"><div class="stat"><h3>Ventas hoy</h3><div class="num">${money(total)}</div></div><div class="stat"><h3>Caja</h3><div class="num">${db.caja.abierta?'Abierta':'Cerrada'}</div></div><div class="stat"><h3>Productos</h3><div class="num">${db.productos.length}</div></div><div class="stat"><h3>Stock bajo</h3><div class="num">${low.length}</div></div></div><div class="grid g2"><div class="panel"><h2>Alertas</h2>${low.length?low.map(p=>`<p>⚠ ${p.descripcion} — stock ${p.stock}</p>`).join(''):'<p class="muted">Sin alertas de stock.</p>'}</div><div class="panel"><h2>Últimas ventas</h2>${db.ventas.slice(0,6).map(v=>`<p>${v.numero} · ${money(v.total)} · ${v.pago}</p>`).join('')||'<p class="muted">Sin ventas.</p>'}</div></div>`; }
function productos(){ return `<h1>Productos</h1><div class="panel"><div class="toolbar"><input id="qProd" placeholder="Buscar por código, barra o descripción" oninput="renderProductTable()"><button onclick="newProduct()">Nuevo</button><button class="secondary" onclick="exportCSV('productos')">Exportar CSV</button></div><div id="productForm"></div><div id="productTable"></div></div>`; }
function renderProductTable(){ const q=($('#qProd')?.value||'').toLowerCase(); const rows=db.productos.filter(p=>[p.codigo,p.barra,p.descripcion,p.marca,p.categoria].join(' ').toLowerCase().includes(q)); $('#productTable').innerHTML=`<table class="table"><tr><th>Código</th><th>Barra</th><th>Descripción</th><th>Categoría</th><th>Precio</th><th>Stock</th><th>Acciones</th></tr>${rows.map(p=>`<tr><td>${p.codigo}</td><td>${p.barra||''}</td><td>${p.descripcion}</td><td>${p.categoria}</td><td>${money(p.precio)}</td><td><span class="pill ${p.stock<=p.minimo?'low':'okpill'}">${p.stock}</span></td><td><button class="secondary" onclick="editProduct(${p.id})">Editar</button> <button class="danger" onclick="deleteProduct(${p.id})">Eliminar</button></td></tr>`).join('')}</table>`; }
function productForm(p={}){ const cats=db.categorias, marks=db.marcas, prov=db.proveedores.map(x=>x.nombre); return `<div class="panel"><h2>${p.id?'Editar':'Nuevo'} producto</h2><div class="form"><div><label>Código</label><input id="f_codigo" value="${p.codigo||nextCode()}"></div><div><label>Código de barras</label><input id="f_barra" value="${p.barra||''}"></div><div class="wide"><label>Descripción</label><input id="f_desc" value="${p.descripcion||''}"></div><div><label>Marca</label><select id="f_marca">${marks.map(x=>`<option ${x==p.marca?'selected':''}>${x}</option>`).join('')}</select></div><div><label>Categoría</label><select id="f_cat">${cats.map(x=>`<option ${x==p.categoria?'selected':''}>${x}</option>`).join('')}</select></div><div><label>Proveedor</label><select id="f_prov">${prov.map(x=>`<option ${x==p.proveedor?'selected':''}>${x}</option>`).join('')}</select></div><div><label>Costo</label><input id="f_costo" type="number" value="${p.costo||0}"></div><div><label>Precio venta</label><input id="f_precio" type="number" value="${p.precio||0}"></div><div><label>IVA %</label><input id="f_iva" type="number" value="${p.iva??21}"></div><div><label>Stock</label><input id="f_stock" type="number" value="${p.stock||0}"></div><div><label>Stock mínimo</label><input id="f_min" type="number" value="${p.minimo||0}"></div><div class="full toolbar"><button onclick="saveProduct()">Guardar</button><button class="secondary" onclick="cancelProduct()">Cancelar</button></div></div></div>`; }
function nextCode(){ return 'P'+String((Math.max(0,...db.productos.map(p=>p.id))+1)).padStart(6,'0'); }
window.newProduct=()=>{editingProduct=null; $('#productForm').innerHTML=productForm({});};
window.editProduct=id=>{editingProduct=db.productos.find(p=>p.id===id); $('#productForm').innerHTML=productForm(editingProduct);};
window.cancelProduct=()=>{$('#productForm').innerHTML='';};
window.saveProduct=async()=>{ const p={id:editingProduct?.id||Date.now(),codigo:$('#f_codigo').value,barra:$('#f_barra').value,descripcion:$('#f_desc').value,marca:$('#f_marca').value,categoria:$('#f_cat').value,proveedor:$('#f_prov').value,costo:+$('#f_costo').value,precio:+$('#f_precio').value,iva:+$('#f_iva').value,stock:+$('#f_stock').value,minimo:+$('#f_min').value,activo:true,createdAt:editingProduct?.createdAt||new Date().toISOString()}; if(!p.descripcion)return alert('Falta descripción'); const i=db.productos.findIndex(x=>x.id===p.id); if(i>=0) db.productos[i]=p; else db.productos.unshift(p); await save('PRODUCTO_GUARDADO',p.descripcion); };
window.deleteProduct=async id=>{ if(!confirm('¿Eliminar producto?'))return; const p=db.productos.find(x=>x.id===id); db.productos=db.productos.filter(x=>x.id!==id); await save('PRODUCTO_ELIMINADO',p?.descripcion||id); };
function ventas(){ return `<h1>Ventas</h1><div class="pos"><div class="panel"><label>Código / lector de barras / búsqueda</label><input id="scan" placeholder="Escanear, escribir código o nombre y ENTER" onkeydown="if(event.key==='Enter')addScan()"><table class="table"><tr><th>Producto</th><th>Cant.</th><th>Precio</th><th>Total</th><th></th></tr>${cart.map((i,idx)=>`<tr><td>${i.descripcion}</td><td><input value="${i.cantidad}" type="number" onchange="cart[${idx}].cantidad=+this.value;render()"></td><td>${money(i.precio)}</td><td>${money(i.precio*i.cantidad)}</td><td><button class="danger" onclick="cart.splice(${idx},1);render()">X</button></td></tr>`).join('')}</table></div><div class="panel"><h2>Total</h2><div class="total">${money(cartTotal())}</div><label>Cliente</label><select id="saleClient">${db.clientes.map(c=>`<option value="${c.id}">${c.nombre}</option>`).join('')}</select><label>Medio de pago</label><select id="pay"><option>Efectivo</option><option>Débito</option><option>Crédito</option><option>Transferencia</option><option>Mercado Pago QR</option><option>Mercado Pago Point - Simulado</option><option>Mixto</option></select><div class="toolbar"><button class="ok" onclick="finishSale()">F6 Cobrar</button><button class="secondary" onclick="cart=[];render()">Cancelar</button></div><p class="muted">La lectora USB funcionará como teclado. El ticket por ahora se genera en TXT.</p></div></div>`; }
function cartTotal(){return cart.reduce((a,i)=>a+i.precio*i.cantidad,0);} 
window.addScan=()=>{ const val=$('#scan').value.trim().toLowerCase(); if(!val)return; let p=db.productos.find(x=>[x.codigo,x.barra].includes(val))||db.productos.find(x=>x.descripcion.toLowerCase().includes(val)); if(!p)return alert('Producto no encontrado'); const ex=cart.find(i=>i.id===p.id); if(ex) ex.cantidad++; else cart.push({id:p.id,descripcion:p.descripcion,precio:p.precio,cantidad:1}); render(); };
window.finishSale=async()=>{ if(!cart.length)return alert('No hay productos'); if(!db.caja.abierta)return alert('Debe abrir la caja antes de vender'); const venta={id:Date.now(),numero:'VTA-'+String(db.ventas.length+1).padStart(6,'0'),fecha:new Date().toISOString(),usuario:user.usuario,cliente:+$('#saleClient').value,pago:$('#pay').value,items:cart,total:cartTotal()}; for(const it of cart){ const p=db.productos.find(x=>x.id===it.id); if(p)p.stock-=it.cantidad; } db.ventas.unshift(venta); db.caja.movimientos.unshift({fecha:new Date().toISOString(),tipo:'VENTA',detalle:venta.numero,monto:venta.total,pago:venta.pago,usuario:user.usuario}); cart=[]; await window.api.ticket(venta,db.negocio); await save('VENTA_REALIZADA',venta.numero+' '+money(venta.total)); };
function caja(){ const total=db.caja.movimientos.reduce((a,m)=>a+(m.tipo==='RETIRO'?-m.monto:m.monto),Number(db.caja.saldoInicial||0)); return `<h1>Caja</h1><div class="grid g3"><div class="stat"><h3>Estado</h3><div class="num">${db.caja.abierta?'Abierta':'Cerrada'}</div></div><div class="stat"><h3>Saldo estimado</h3><div class="num">${money(total)}</div></div><div class="stat"><h3>Movimientos</h3><div class="num">${db.caja.movimientos.length}</div></div></div><div class="panel"><div class="toolbar"><input id="saldo" type="number" placeholder="Saldo inicial / monto"><button onclick="openCash()">Abrir caja</button><button class="danger" onclick="closeCash()">Cerrar caja</button><button class="secondary" onclick="cashMov('INGRESO')">Ingreso</button><button class="secondary" onclick="cashMov('RETIRO')">Retiro</button></div><table class="table"><tr><th>Fecha</th><th>Tipo</th><th>Detalle</th><th>Monto</th></tr>${db.caja.movimientos.slice(0,30).map(m=>`<tr><td>${new Date(m.fecha).toLocaleString('es-AR')}</td><td>${m.tipo}</td><td>${m.detalle}</td><td>${money(m.monto)}</td></tr>`).join('')}</table></div>`; }
window.openCash=async()=>{ if(db.caja.abierta)return alert('Caja ya abierta'); db.caja={abierta:true,fecha:new Date().toISOString(),usuario:user.usuario,saldoInicial:+($('#saldo').value||0),movimientos:[]}; await save('CAJA_ABIERTA',money(db.caja.saldoInicial)); };
window.closeCash=async()=>{ if(!db.caja.abierta)return; db.caja.abierta=false; await save('CAJA_CERRADA','Cierre de caja'); };
window.cashMov=async tipo=>{ const monto=+($('#saldo').value||0); if(!monto)return alert('Ingrese monto'); db.caja.movimientos.unshift({fecha:new Date().toISOString(),tipo,detalle:'Movimiento manual',monto,usuario:user.usuario}); await save('CAJA_MOVIMIENTO',tipo+' '+money(monto)); };
function stock(){ return `<h1>Stock</h1><div class="panel"><table class="table"><tr><th>Producto</th><th>Categoría</th><th>Stock</th><th>Mínimo</th><th>Estado</th></tr>${db.productos.map(p=>`<tr><td>${p.descripcion}</td><td>${p.categoria}</td><td>${p.stock}</td><td>${p.minimo}</td><td>${p.stock<=p.minimo?'<span class="pill low">Bajo</span>':'<span class="pill okpill">OK</span>'}</td></tr>`).join('')}</table></div>`; }
function clientes(){ return crudSimple('Clientes','clientes',['nombre','dni','telefono','email']); }
function proveedores(){ return crudSimple('Proveedores','proveedores',['nombre','telefono','email','direccion']); }
function crudSimple(title,key,fields){ return `<h1>${title}</h1><div class="panel"><div class="toolbar">${fields.map(f=>`<input id="${key}_${f}" placeholder="${f}">`).join('')}<button onclick="addSimple('${key}','${fields.join(',')}')">Agregar</button></div><table class="table"><tr>${fields.map(f=>`<th>${f}</th>`).join('')}<th></th></tr>${db[key].map(x=>`<tr>${fields.map(f=>`<td>${x[f]||''}</td>`).join('')}<td><button class="danger" onclick="delSimple('${key}',${x.id})">Eliminar</button></td></tr>`).join('')}</table></div>`; }
window.addSimple=async(key,fields)=>{ const fs=fields.split(','); const obj={id:Date.now(),activo:true}; fs.forEach(f=>obj[f]=$(`#${key}_${f}`).value); db[key].unshift(obj); await save(key.toUpperCase()+'_AGREGADO',obj.nombre||''); };
window.delSimple=async(key,id)=>{ db[key]=db[key].filter(x=>x.id!==id); await save(key.toUpperCase()+'_ELIMINADO',String(id)); };
function reportes(){ const total=db.ventas.reduce((a,v)=>a+v.total,0); return `<h1>Reportes</h1><div class="grid g3"><div class="stat"><h3>Total vendido</h3><div class="num">${money(total)}</div></div><div class="stat"><h3>Tickets</h3><div class="num">${db.ventas.length}</div></div><div class="stat"><h3>Ticket promedio</h3><div class="num">${money(db.ventas.length?total/db.ventas.length:0)}</div></div></div><div class="panel"><h2>Ventas</h2><table class="table"><tr><th>Ticket</th><th>Fecha</th><th>Pago</th><th>Total</th></tr>${db.ventas.map(v=>`<tr><td>${v.numero}</td><td>${new Date(v.fecha).toLocaleString('es-AR')}</td><td>${v.pago}</td><td>${money(v.total)}</td></tr>`).join('')}</table></div>`; }
function config(){ const n=db.negocio; return `<h1>Configuración</h1><div class="panel"><div class="form">${['nombre','razonSocial','cuit','direccion','telefono','email','iva','impresora','ticketMm'].map(f=>`<div><label>${f}</label><input id="cfg_${f}" value="${n[f]||''}"></div>`).join('')}<div class="full toolbar"><button onclick="saveConfig()">Guardar configuración</button></div></div></div>`; }
window.saveConfig=async()=>{ ['nombre','razonSocial','cuit','direccion','telefono','email','iva','impresora','ticketMm'].forEach(f=>db.negocio[f]=$(`#cfg_${f}`).value); await save('CONFIG_GUARDADA','Datos del comercio'); };
function tecnico(){ return `<h1>Panel Técnico</h1><div class="grid g3"><div class="stat"><h3>Base local</h3><div class="num">OK</div></div><div class="stat"><h3>PC</h3><div class="num">Local</div></div><div class="stat"><h3>Versión</h3><div class="num">0.5</div></div></div><div class="panel"><div class="toolbar"><button onclick="doBackup()">Crear backup</button><button class="secondary" onclick="exportCSV('ventas')">Exportar ventas CSV</button></div><h2>Auditoría</h2><table class="table"><tr><th>Fecha</th><th>Usuario</th><th>Acción</th><th>Detalle</th></tr>${db.auditoria.slice(0,50).map(a=>`<tr><td>${new Date(a.fecha).toLocaleString('es-AR')}</td><td>${a.usuario}</td><td>${a.accion}</td><td>${a.detalle}</td></tr>`).join('')}</table></div>`; }
window.doBackup=async()=>{ const f=await window.api.backup(); alert('Backup creado:\n'+f); };
window.exportCSV=(type)=>{ let rows=[]; if(type==='productos') rows=[['codigo','barra','descripcion','marca','categoria','precio','stock'],...db.productos.map(p=>[p.codigo,p.barra,p.descripcion,p.marca,p.categoria,p.precio,p.stock])]; else rows=[['numero','fecha','usuario','pago','total'],...db.ventas.map(v=>[v.numero,v.fecha,v.usuario,v.pago,v.total])]; const csv=rows.map(r=>r.map(x=>`"${String(x??'').replace(/"/g,'""')}"`).join(';')).join('\n'); const blob=new Blob([csv],{type:'text/csv'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`${type}.csv`; a.click(); };
init();
