let state={user:null,data:null,cart:[],editingProduct:null};
const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
function money(n){return Number(n||0).toLocaleString('es-AR',{style:'currency',currency:'ARS'});} 
function esc(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));}
	var api = window.dataService || window.api;
async function refresh(){ state.data=await api.getState(); $('#bizName').textContent=state.data.business.nombre||'PetroPOS'; }
function setView(v){ $$('.sidebar nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v)); const map={dashboard,ventas,productos,catalogos,config,auditoria,tecnico}; map[v](); }
function options(arr, selected=''){ return arr.map(x=>`<option ${x===selected?'selected':''}>${esc(x)}</option>`).join(''); }

document.addEventListener('DOMContentLoaded',()=>{
 $('#btnLogin').onclick=login; $('#loginPass').addEventListener('keydown',e=>{if(e.key==='Enter')login();});
 $$('.sidebar nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));
 $('#btnBackup').onclick=async()=>{const r=await api.backup({user:state.user}); alert(r.ok?'Backup generado:\n'+r.file:'Error'); await refresh();};
 setInterval(()=>$('#clock').textContent=new Date().toLocaleString('es-AR'),1000);
});
async function login(){ const r=await api.login({usuario:$('#loginUser').value.trim(),clave:$('#loginPass').value}); if(!r.ok){$('#loginMsg').textContent=r.msg;return;} state.user=r.user; $('#userName').textContent=`${r.user.nombre} (${r.user.rol})`; $('#login').classList.add('hidden'); $('#app').classList.remove('hidden'); await refresh(); setView('dashboard'); }

function dashboard(){ const d=state.data.dashboard; $('#content').innerHTML=`<div class="section-title"><h2>🏠 Centro de Control</h2><div class="muted">PetroPOS v0.3.0 - Fundación</div></div><div class="grid cards"><div class="card"><div class="label">Facturado hoy</div><div class="value">${money(d.facturadoHoy)}</div></div><div class="card"><div class="label">Ventas hoy</div><div class="value">${d.ventasHoy}</div></div><div class="card"><div class="label">Productos</div><div class="value">${d.productos}</div></div><div class="card"><div class="label">Stock bajo</div><div class="value">${d.stockBajo}</div></div><div class="card"><div class="label">Última venta</div><div class="value">${d.ultimaVenta}</div></div></div><br><div class="grid" style="grid-template-columns:1.2fr .8fr"><div class="card"><h3>Ventas recientes</h3>${salesTable(state.data.sales)}</div><div class="card"><h3>Notificaciones</h3><p class="notice">Lector de código de barras: preparado. Hasta tener la pistola, escribí el código manualmente y presioná ENTER.</p><p class="notice">Ticketera: preparada. Por ahora el ticket se genera como TXT y se abre para revisar.</p></div></div>`; }
function salesTable(sales){ if(!sales.length) return '<p class="muted">Sin ventas todavía.</p>'; return `<table><thead><tr><th>Ticket</th><th>Fecha</th><th>Pago</th><th class="right">Total</th></tr></thead><tbody>${sales.map(s=>`<tr><td>${s.numero}</td><td>${new Date(s.fecha).toLocaleString('es-AR')}</td><td>${s.payment}</td><td class="right">${money(s.total)}</td></tr>`).join('')}</tbody></table>`; }

function productos(){ $('#content').innerHTML=`<div class="section-title"><h2>📦 Productos</h2><div class="toolbar"><input id="qProd" placeholder="Buscar por código, descripción, marca..."><button id="btnNewProd">Nuevo</button></div></div><div class="layout-2"><div class="card"><h3 id="formTitle">Nuevo producto</h3><div class="form"><input id="pCodigo" placeholder="Código de barras"><input id="pDesc" placeholder="Descripción"><div class="form-row"><select id="pMarca">${options(state.data.brands)}</select><select id="pCat">${options(state.data.categories)}</select></div><select id="pProv">${options(state.data.suppliers)}</select><div class="form-row"><input id="pCosto" type="number" placeholder="Costo"><input id="pPrecio" type="number" placeholder="Precio venta"></div><div class="form-row"><input id="pStock" type="number" placeholder="Stock"><input id="pStockMin" type="number" placeholder="Stock mínimo"></div><div class="form-row"><input id="pIva" type="number" value="21" placeholder="IVA"><select id="pActivo"><option value="true">Activo</option><option value="false">Inactivo</option></select></div><button id="btnSaveProd" class="green">Guardar producto</button><button id="btnCancelProd" class="secondary">Cancelar</button></div></div><div class="card"><div id="prodTable"></div></div></div>`; bindProductos(); renderProdTable(); }
function bindProductos(){ $('#qProd').oninput=renderProdTable; $('#btnNewProd').onclick=clearProd; $('#btnCancelProd').onclick=clearProd; $('#btnSaveProd').onclick=saveProd; }
function productRows(){ const q=($('#qProd')?.value||'').toLowerCase(); return state.data.products.filter(p=>[p.codigo,p.interno,p.descripcion,p.marca,p.categoria].join(' ').toLowerCase().includes(q)); }
function renderProdTable(){ const rows=productRows(); $('#prodTable').innerHTML=`<table><thead><tr><th>Código</th><th>Descripción</th><th>Cat.</th><th>Stock</th><th>Precio</th><th>Estado</th><th></th></tr></thead><tbody>${rows.map(p=>`<tr><td>${esc(p.codigo)}</td><td><b>${esc(p.descripcion)}</b><br><span class="muted">${p.interno} · ${esc(p.marca)}</span></td><td>${esc(p.categoria)}</td><td>${Number(p.stock)<=Number(p.stockMin)?`<span class="pill red">${p.stock}</span>`:`<span class="pill green">${p.stock}</span>`}</td><td>${money(p.precio)}</td><td>${p.activo?'<span class="pill green">Activo</span>':'<span class="pill red">Inactivo</span>'}</td><td><button class="secondary" onclick="editProd(${p.id})">Editar</button> <button class="danger" onclick="delProd(${p.id})">Baja</button></td></tr>`).join('')}</tbody></table>`; }
function clearProd(){ state.editingProduct=null; $('#formTitle').textContent='Nuevo producto'; ['pCodigo','pDesc','pCosto','pPrecio','pStock','pStockMin'].forEach(id=>$('#'+id).value=''); $('#pIva').value=21; $('#pActivo').value='true'; }
window.editProd=(id)=>{ const p=state.data.products.find(x=>x.id===id); state.editingProduct=p; $('#formTitle').textContent='Editando: '+p.descripcion; $('#pCodigo').value=p.codigo; $('#pDesc').value=p.descripcion; $('#pMarca').value=p.marca; $('#pCat').value=p.categoria; $('#pProv').value=p.proveedor; $('#pCosto').value=p.costo; $('#pPrecio').value=p.precio; $('#pStock').value=p.stock; $('#pStockMin').value=p.stockMin; $('#pIva').value=p.iva; $('#pActivo').value=String(p.activo); };
window.delProd=async(id)=>{ if(!confirm('¿Dar de baja este producto?'))return; await api.deleteProduct({id,user:state.user}); await refresh(); productos(); };
async function saveProd(){ const product={id:state.editingProduct?.id,codigo:$('#pCodigo').value.trim(),descripcion:$('#pDesc').value.trim(),marca:$('#pMarca').value,categoria:$('#pCat').value,proveedor:$('#pProv').value,costo:$('#pCosto').value||0,precio:$('#pPrecio').value||0,stock:$('#pStock').value||0,stockMin:$('#pStockMin').value||0,iva:$('#pIva').value||21,activo:$('#pActivo').value==='true'}; if(!product.descripcion){alert('Cargá una descripción');return;} await api.saveProduct({product,user:state.user}); await refresh(); productos(); }

function ventas(){ state.cart=[]; $('#content').innerHTML=`<div class="section-title"><h2>💰 Venta rápida</h2><div class="muted">Preparado para lectora USB</div></div><div class="pos"><div class="card"><div class="toolbar"><input id="scan" placeholder="Escanear o escribir código / nombre y ENTER" style="flex:1"><button id="btnSearchAdd">Agregar</button></div><br><div class="items-list" id="cart"></div></div><div class="card"><h3>Cobro</h3><div class="big-total" id="total">$0,00</div><br><select id="payment"><option>Efectivo</option><option>Débito</option><option>Crédito</option><option>Transferencia</option><option>Mercado Pago QR</option><option>Mercado Pago Point (simulado)</option><option>Mixto</option></select><br><br><button class="green" id="btnCobrar" style="width:100%;font-size:20px">F6 Cobrar</button><br><br><button class="secondary" id="btnClear" style="width:100%">Cancelar venta</button><hr><p class="muted">Atajos: ENTER agrega producto · F6 cobra · ESC cancela.</p></div></div>`; bindVentas(); renderCart(); }
function bindVentas(){ $('#scan').focus(); $('#scan').addEventListener('keydown',e=>{ if(e.key==='Enter') addByScan();}); $('#btnSearchAdd').onclick=addByScan; $('#btnCobrar').onclick=cobrar; $('#btnClear').onclick=()=>{state.cart=[];renderCart();}; document.onkeydown=e=>{ if(!$('#app').classList.contains('hidden') && $$('.sidebar nav button.active')[0]?.dataset.view==='ventas'){ if(e.key==='F6'){e.preventDefault();cobrar();} if(e.key==='Escape'){state.cart=[];renderCart();}}}; }
function addByScan(){ const q=$('#scan').value.trim().toLowerCase(); if(!q)return; let p=state.data.products.find(x=>x.activo && (x.codigo||'').toLowerCase()===q) || state.data.products.find(x=>x.activo && (x.descripcion||'').toLowerCase().includes(q)); if(!p){ alert('Producto no encontrado'); return; } const it=state.cart.find(x=>x.id===p.id); if(it) it.cantidad++; else state.cart.push({id:p.id,codigo:p.codigo,descripcion:p.descripcion,precio:Number(p.precio),cantidad:1}); $('#scan').value=''; renderCart(); }
function renderCart(){ const total=state.cart.reduce((a,i)=>a+i.precio*i.cantidad,0); $('#total') && ($('#total').textContent=money(total)); if(!$('#cart'))return; $('#cart').innerHTML= state.cart.length? `<table><thead><tr><th>Producto</th><th>Cant.</th><th>Precio</th><th>Total</th><th></th></tr></thead><tbody>${state.cart.map((i,idx)=>`<tr><td>${esc(i.descripcion)}<br><span class="muted">${esc(i.codigo)}</span></td><td><input class="qty" type="number" min="1" value="${i.cantidad}" onchange="changeQty(${idx},this.value)"></td><td>${money(i.precio)}</td><td>${money(i.precio*i.cantidad)}</td><td><button class="danger" onclick="removeItem(${idx})">X</button></td></tr>`).join('')}</tbody></table>`:'<p class="muted">Venta vacía.</p>'; }
window.changeQty=(idx,val)=>{state.cart[idx].cantidad=Math.max(1,Number(val||1));renderCart();}; window.removeItem=(idx)=>{state.cart.splice(idx,1);renderCart();};
async function cobrar(){ if(!state.cart.length){alert('No hay productos en la venta');return;} const r=await api.newSale({items:state.cart,payment:$('#payment').value,user:state.user}); if(!r.ok){alert(r.msg);return;} alert('Venta generada: '+r.sale.numero); state.cart=[]; await refresh(); ventas(); }

function catalogos(){ $('#content').innerHTML=`<div class="section-title"><h2>🏷 Catálogos</h2></div><div class="grid" style="grid-template-columns:repeat(3,1fr)">${catalogBox('category','Categorías',state.data.categories)}${catalogBox('brand','Marcas',state.data.brands)}${catalogBox('supplier','Proveedores',state.data.suppliers)}</div>`; }
function catalogBox(type,title,arr){ return `<div class="card"><h3>${title}</h3><div class="toolbar"><input id="${type}Input" placeholder="Nuevo"><button onclick="addCatalog('${type}')">Agregar</button></div><br>${arr.map(x=>`<span class="pill">${esc(x)}</span>`).join(' ')}</div>`; }
window.addCatalog=async(type)=>{ const value=$('#'+type+'Input').value.trim(); if(!value)return; await api.addCatalogValue({type,value,user:state.user}); await refresh(); catalogos(); };

function config(){ const b=state.data.business; $('#content').innerHTML=`<div class="section-title"><h2>⚙ Configuración del negocio</h2></div><div class="card"><div class="form"><div class="form-row"><input id="bNombre" placeholder="Nombre comercio" value="${esc(b.nombre)}"><input id="bRazon" placeholder="Razón social" value="${esc(b.razonSocial)}"></div><div class="form-row"><input id="bCuit" placeholder="CUIT" value="${esc(b.cuit)}"><input id="bIva" placeholder="Condición IVA" value="${esc(b.iva)}"></div><input id="bDom" placeholder="Domicilio" value="${esc(b.domicilio)}"><div class="form-row"><input id="bTel" placeholder="Teléfono" value="${esc(b.telefono)}"><input id="bEmail" placeholder="Email" value="${esc(b.email)}"></div><div class="form-row"><input id="bMoneda" placeholder="Moneda" value="${esc(b.moneda)}"><input id="bLeyenda" placeholder="Leyenda ticket" value="${esc(b.ticketLeyenda)}"></div><button class="green" id="saveBiz">Guardar configuración</button></div></div>`; $('#saveBiz').onclick=async()=>{await api.saveBusiness({user:state.user,business:{nombre:$('#bNombre').value,razonSocial:$('#bRazon').value,cuit:$('#bCuit').value,iva:$('#bIva').value,domicilio:$('#bDom').value,telefono:$('#bTel').value,email:$('#bEmail').value,moneda:$('#bMoneda').value,ticketLeyenda:$('#bLeyenda').value}}); await refresh(); alert('Configuración guardada'); config();}; }
function auditoria(){ $('#content').innerHTML=`<div class="section-title"><h2>📖 Auditoría</h2></div><div class="audit-list">${state.data.audits.map(a=>`<div class="audit-item"><b>${esc(a.accion)}</b> · ${esc(a.usuario)} <small>${new Date(a.fecha).toLocaleString('es-AR')}</small><br><span class="muted">${esc(a.detalle)}</span></div>`).join('')||'<p class="muted">Sin registros.</p>'}</div>`; }
function tecnico(){ $('#content').innerHTML=`<div class="section-title"><h2>🔧 Panel técnico</h2></div><div class="grid cards"><div class="card"><div class="label">Versión</div><div class="value">0.3.0</div></div><div class="card"><div class="label">Base</div><div class="value">OK</div></div><div class="card"><div class="label">Ticketera</div><div class="value">TXT</div></div><div class="card"><div class="label">Lector</div><div class="value">USB</div></div><div class="card"><div class="label">Modo</div><div class="value">Local</div></div></div><br><div class="card"><h3>Checklist actual</h3><p>✅ Compatible con Windows 7/10/11 usando Electron 22.</p><p>✅ Datos separados del programa.</p><p>✅ Backups manuales.</p><p>✅ Preparado para lectora y ticketera.</p><p>⏳ Próximo: caja completa, medios de pago avanzados, ticketera directa.</p></div>`; }
